//
// Generated file, do not edit! Created by nedtool 5.6 from AppMessageStatus.msg.
//

#ifndef __APPMESSAGESTATUS_M_H
#define __APPMESSAGESTATUS_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Enum generated from <tt>AppMessageStatus.msg:2</tt> by nedtool.
 * <pre>
 * enum AppMessageStatus
 * {
 *     Success = 0;
 *     BufferDrop = 1;
 *     ChannelFailure = 2;
 * }
 * </pre>
 */
enum AppMessageStatus {
    Success = 0,
    BufferDrop = 1,
    ChannelFailure = 2
};


#endif // ifndef __APPMESSAGESTATUS_M_H

