//
// Generated file, do not edit! Created by nedtool 5.6 from AppMessage.msg.
//

#ifndef __APPMESSAGE_M_H
#define __APPMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>AppMessage.msg:1</tt> by nedtool.
 * <pre>
 * packet AppMessage
 * {
 *     simtime_t timestamp;
 *     int senderAddress;
 *     int receiverAddress;
 *     int sequenceNumber;
 * }
 * </pre>
 */
class AppMessage : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::simtime_t timestamp;
    int senderAddress;
    int receiverAddress;
    int sequenceNumber;

  private:
    void copy(const AppMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AppMessage&);

  public:
    AppMessage(const char *name=nullptr, short kind=0);
    AppMessage(const AppMessage& other);
    virtual ~AppMessage();
    AppMessage& operator=(const AppMessage& other);
    virtual AppMessage *dup() const override {return new AppMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual ::omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(::omnetpp::simtime_t timestamp);
    virtual int getSenderAddress() const;
    virtual void setSenderAddress(int senderAddress);
    virtual int getReceiverAddress() const;
    virtual void setReceiverAddress(int receiverAddress);
    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AppMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AppMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __APPMESSAGE_M_H

