//
// Generated file, do not edit! Created by nedtool 5.6 from AppResponse.msg.
//

#ifndef __APPRESPONSE_M_H
#define __APPRESPONSE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "AppMessageStatus_m.h"
// }}

/**
 * Class generated from <tt>AppResponse.msg:7</tt> by nedtool.
 * <pre>
 * message AppResponse
 * {
 *     int sequenceNumber;
 *     int outcome \@enum(AppMessageStatus);
 * }
 * </pre>
 */
class AppResponse : public ::omnetpp::cMessage
{
  protected:
    int sequenceNumber;
    int outcome;

  private:
    void copy(const AppResponse& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AppResponse&);

  public:
    AppResponse(const char *name=nullptr, short kind=0);
    AppResponse(const AppResponse& other);
    virtual ~AppResponse();
    AppResponse& operator=(const AppResponse& other);
    virtual AppResponse *dup() const override {return new AppResponse(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);
    virtual int getOutcome() const;
    virtual void setOutcome(int outcome);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AppResponse& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AppResponse& obj) {obj.parsimUnpack(b);}


#endif // ifndef __APPRESPONSE_M_H

